#! /usr/bin/env toml
# /qompassai/Diver/pixi.toml
# Qompass AI Diver Pixi Config
# Copyright (C) 2026 Qompass AI, All rights reserved
# ----------------------------------------
[project]
name = "nvim-mojo"
channels = [
  "https://conda.modular.com/max-nightly",
  "https://conda.modular.com/max",
  "conda-forge"
]
platforms = ["linux-64"]
version = "1.0.0"

[dependencies]
mojo = "*"
max = "*"

[activation.env]
MOJO_STDLIB_PATH = "$PIXI_PROJECT_ROOT/.pixi/envs/default/lib/mojo"
MODULAR_HOME = "$PIXI_PROJECT_ROOT/.pixi/envs/default"
